# Generated by Django 4.2.2 on 2023-09-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_machines_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='name',
            field=models.CharField(default='Valor Predeterminado', max_length=100),
        ),
    ]
