# Generated by Django 4.2.5 on 2023-12-07 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_alter_machines_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='code',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='comments',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='equip',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='brand',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='responsible',
            new_name='responsable',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='department',
        ),
        migrations.AlterField(
            model_name='machines',
            name='area',
            field=models.CharField(blank=True, choices=[('Acabado Grafico', 'Acabado Grafico'), ('Acabado Industrial', 'Acabado Industrial'), ('Digital', 'Digital'), ('Diseño', 'Diseño'), ('Flexo', 'Flexo'), ('Gran Formato', 'Gran Formato'), ('Offset', 'Offset'), ('Talleres', 'Talleres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='machines',
            name='manual',
            field=models.FileField(upload_to='manuals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
