# Generated by Django 4.2.5 on 2023-12-07 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machines', to_field='nombre'),
        ),
        migrations.AlterField(
            model_name='machines',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
