# Generated by Django 4.2.5 on 2023-12-12 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_alter_bitacora_maquina_alter_machines_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='usuario',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bitacora/'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machines'),
        ),
    ]
