# Generated by Django 4.2.2 on 2023-09-21 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, choices=[('Acabado Grafico', 'Acabado Grafico'), ('Acabado Industrial', 'Acabado Industrial'), ('Gran Formato', 'Gran Formato'), ('Impresión', 'Impresión'), ('Prensas', 'Prensas'), ('Prensa', 'Prensa')], max_length=100)),
                ('area', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Diseño', 'Diseño'), ('Flexo', 'Flexo'), ('Gran Formato', 'Gran Formato'), ('Offset', 'Offset'), ('Talleres', 'Talleres')], max_length=100)),
                ('responsible', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
