# Generated by Django 4.2.2 on 2023-09-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewMachines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinepost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
    ]
