# Generated by Django 4.2.2 on 2023-09-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewMachines', '0002_machinepost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinepost',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
