# Generated by Django 4.2.2 on 2023-09-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewMachines', '0003_machinepost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinepost',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
